### ISSUE TITLE
白名单功能似乎未能正常生效

### ISSUE THREAD

**Issue by KotoriTaiho** [NewYearPrism/nonebot-plugin-ocr#1]
配置信息是从配置模板文件中复制来的，仅修改调整过apikey和识别语言模式的配置，白名单选项中不管是配置群号还是配置用户QQ机器人都没有反应

**Comment by NewYearPrism** [comment]
能否提供相关日志信息

**Comment by KotoriTaiho** [comment]
好像没有办法提供，插件目前对除了nonebot超级用户外的其他用户（加入白名单后）使用指令后控制台都不会有响应以及相关的日志的输出，已尝试在配置文件中将群号或者指定用户或者两者都加入白名单进行测试仍未响应
![$A}P)IQ7C_2O1_O0O$UG% S](https://user-images.githubusercontent.com/53947653/194277958-51e69a47-ca9f-4ea1-a1ee-c1fb21484676.png)
![MSJZ`MNO1E4Z5$40~Z9KR3O](https://user-images.githubusercontent.com/53947653/194278113-bb1dc30a-0e39-45c6-b728-8da8d0eec261.png)
如果是超级用户则仍会正常响应并有相关日志输出，之前有尝试通过修改插件配置文件中的其他配置项以验证配置文件是能正常被插件加载的
![FBWR4AIX(}{FN}A)L{~}}1U](https://user-images.githubusercontent.com/53947653/194279407-32288c6e-1cdf-4dc3-ab6a-2ce4507179b8.png)

**Comment by NewYearPrism** [comment]
已复现问题并修复，请更新插件并确认

**Comment by KotoriTaiho** [comment]
更新后已可以使用，感谢
